#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  namespace: anotherclass-212
#  name: api-tester-2121-files
#  labels:
#    part-of: k8s-anotherclass
#    component: backend-server
#    name: api-tester
#    instance: api-tester-2121
#    version: 1.0.0
#    managed-by: kubectl
#spec:
#  accessModes:
#    - ReadWriteMany
#  volumeName: pvc-3945ee73-532c-4e2b-bdda-97f019a156dc
#  storageClassName: azurefile
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 2Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: anotherclass-212
  name: api-tester-2121-files
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2121
    version: 1.0.0
    managed-by: kubectl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: api-tester-2121-files
  resources:
    requests:
      storage: 5Gi
