apiVersion: v1
kind: Service
metadata:
  name: api-tester-2234
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2234
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2234
  ports:
    - port: 80
      targetPort: http
      nodePort: 32234
  type: LoadBalancer
